GET http://localhost:3000/transactions?selectedMonth=03&searchText=3
###

GET http://localhost:3000/statistics?selectedMonth=09
###

GET http://localhost:3000/bar-chart?selectedMonth=11
###

GET http://localhost:3000/pie-chart?selectedMonth=06
###

GET http://localhost:3000/all-roxiler-data?selectedMonth=03&searchText=3
###
###

// DONT DO INITIALIZE DATABASE ALREADY INITIALISED IN CASE DID IT WILL GIVE DUPLICATE VALUES

###



